INSERT INTO edges (type, status, weight, fromNodeId, toNodeId)
SELECT 0, 1, 10.0,
  (SELECT id FROM nodes WHERE code = code1),
  (SELECT id FROM nodes WHERE code = code2)
FROM (
  /* --- Eje Vertical, Entrada a Edificio --- */
  SELECT 'ENTR-F4' AS code1, 'WP-F4-01' AS code2 UNION ALL
  SELECT 'WP-F4-01', 'WP-F4-02' UNION ALL
  SELECT 'WP-F4-02', 'WP-F4-03' UNION ALL
  SELECT 'WP-F4-03', 'WP-F4-04' UNION ALL
  SELECT 'WP-F4-04', 'SECU-F4'  UNION ALL
  SELECT 'WP-F4-17', 'SECU-F4'  UNION ALL
  SELECT 'WP-F4-04', 'EL-EDI-F4' UNION ALL
  SELECT 'WP-F4-21', 'EL-EDI-F4' UNION ALL

  /* --- Eje Horizontal, Entrada a Parqueo --- */
  SELECT 'ENTR-F4', 'WP-F4-05'  UNION ALL
  SELECT 'WP-F4-05', 'WP-F4-06' UNION ALL
  SELECT 'WP-F4-06', 'WP-F4-07' UNION ALL
  SELECT 'WP-F4-07', 'WP-F4-08' UNION ALL
  SELECT 'WP-F4-08', 'WP-F4-09' UNION ALL
  SELECT 'WP-F4-09', 'WP-F4-10' UNION ALL
  SELECT 'WP-F4-10', 'WP-F4-11' UNION ALL
  SELECT 'WP-F4-11', 'WP-F4-12' UNION ALL
  SELECT 'WP-F4-12', 'PARK-F4'  UNION ALL

  /* --- Izquierda Edificio (Aulas y Escaleras) --- */
  SELECT 'WP-F4-04', 'WP-F4-17'  UNION ALL
  SELECT 'WP-F4-17', 'WP-F4-18'  UNION ALL
  SELECT 'WP-F4-18', 'WP-F4-19'  UNION ALL
  SELECT 'WP-F4-19', 'WP-F4-20'  UNION ALL
  SELECT 'WP-F4-20', 'R-316'     UNION ALL
  SELECT 'WP-F4-19', 'R-317'     UNION ALL
  SELECT 'WP-F4-18', 'R-318'     UNION ALL
  SELECT 'WP-F4-20', 'ST-L1-UP-F5' UNION ALL
  SELECT 'WP-F4-20', 'ST-L2-DOWN-F3' UNION ALL

  /* --- Derecha Edificio (Oficinas y Escaleras) --- */
  SELECT 'WP-F4-04', 'WP-F4-21'  UNION ALL
  SELECT 'WP-F4-21', 'WP-F4-22'  UNION ALL
  SELECT 'WP-F4-22', 'WP-F4-23'  UNION ALL
  SELECT 'WP-F4-23', 'WP-F4-24'  UNION ALL
  SELECT 'WP-F4-22', 'OFF-F4-D1' UNION ALL
  SELECT 'WP-F4-23', 'OFF-F4-D2' UNION ALL
  SELECT 'WP-F4-24', 'OFF-F4-D3' UNION ALL
  SELECT 'WP-F4-24', 'ST-R1-UP-F5' UNION ALL
  SELECT 'WP-F4-24', 'ST-R2-DOWN-F3' UNION ALL

  /* --- Eje Vertical, Parqueo a Comedor --- */
  SELECT 'PARK-F4', 'WP-F4-16'  UNION ALL
  SELECT 'WP-F4-16', 'WP-F4-15' UNION ALL
  SELECT 'WP-F4-15', 'WP-F4-14' UNION ALL
  SELECT 'WP-F4-14', 'WP-F4-13' UNION ALL
  SELECT 'WP-F4-13', 'WP-F4-28' UNION ALL

  /* --- Puente y Conexiones de Comedor --- */
  SELECT 'WP-F4-13', 'WP-F4-27' UNION ALL
  SELECT 'WP-F4-27', 'WP-F4-26' UNION ALL
  SELECT 'WP-F4-26', 'WP-F4-25' UNION ALL
  SELECT 'WP-F4-25', 'WP-F4-20' UNION ALL
  SELECT 'WP-F4-27', 'EL-CAF-F4' UNION ALL
  SELECT 'WP-F4-26', 'ST-CAF-DOWN-LIB' UNION ALL

  /* --- Pasillo Final y Baños --- */
  SELECT 'WP-F4-28', 'CAFE-F4' UNION ALL
  SELECT 'CAFE-F4', 'BATH-F4'
) AS n1
WHERE EXISTS (SELECT 1 FROM nodes WHERE code = n1.code1)
  AND EXISTS (SELECT 1 FROM nodes WHERE code = n1.code2);
